/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graf;

import static Lab2.Lab2.toDate;
import ds.FinansuValdymas;
import ds.Kategorija;
import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pacani
 */
public class IslaiduIvedimas extends javax.swing.JDialog {
FinansuValdymas a = new FinansuValdymas();
    /**
     * Creates new form IslaiduIvedimas
     */
    public IslaiduIvedimas(java.awt.Frame parent, boolean modal, FinansuValdymas a) {
        super(parent, modal);
                 this.a = a;
        initComponents();
        ArrayList<Kategorija> kat = a.gautiKategorijuSarasa();
        String[] mas = new String[kat.size()];
        int i=0;
        for(Kategorija k:kat){
            mas[i] = k.getPavadinimas();
            i++;
        }
        i_kategorija.setModel(new javax.swing.DefaultComboBoxModel<>(
                mas
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        i_kategorija = new javax.swing.JComboBox<>();
        i_pavadinimas = new javax.swing.JTextField();
        i_data = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        i_komentaras = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        i_suma = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("islaidos");

        jLabel1.setText("Kategorija:");

        jLabel2.setText("Pavadinimas:");

        jLabel3.setText("Data:");

        jLabel4.setText("Komentaras");

        i_kategorija.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        i_kategorija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_kategorijaActionPerformed(evt);
            }
        });

        i_pavadinimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_pavadinimasActionPerformed(evt);
            }
        });

        i_data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                i_dataKeyReleased(evt);
            }
        });

        i_komentaras.setColumns(20);
        i_komentaras.setRows(5);
        jScrollPane1.setViewportView(i_komentaras);

        jButton1.setText("Ivesti");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Suma");

        i_suma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                i_sumaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(i_kategorija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i_pavadinimas)
                            .addComponent(i_data)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(i_suma))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(i_kategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(i_pavadinimas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(i_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(i_suma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void i_pavadinimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_pavadinimasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_pavadinimasActionPerformed

    private void i_kategorijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_kategorijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_kategorijaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //FinansuValdymas afv = new FinansuValdymas();
        String kpav = this.i_kategorija.getSelectedItem().toString();
        String pav = this.i_pavadinimas.getText();
        String data = this.i_data.getText();
        Date dataaa = toDate(data);
        String kom = this.i_komentaras.getText();
        String strSum = this.i_suma.getText();
        double suma = Double.parseDouble(strSum);
        a.pridetiIslaida(suma,dataaa,pav,kpav,kom,"0");
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void i_dataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_i_dataKeyReleased
        String datNuo = i_data.getText();
        if(((4 == datNuo.indexOf("-")) && (7 == datNuo.indexOf("-",5)) && datNuo.length()==10) 
                && (datNuo.substring(5, 6).equals("0")||datNuo.substring(5, 6).equals("1")
                &&(datNuo.substring(8, 9).equals("0")||datNuo.substring(8, 9).equals("1")
                ||datNuo.substring(8, 9).equals("2")||datNuo.substring(8, 9).equals("3")))){
            i_data.setBackground(Color.white);
            jButton1.setEnabled(true);

        }else{
            i_data.setBackground(Color.red);
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_i_dataKeyReleased

    private void i_sumaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_i_sumaKeyReleased
        try{
            Double.parseDouble(i_suma.getText());
            i_suma.setBackground(Color.white);
            try{
            Double.parseDouble(i_suma.getText());
            jButton1.setEnabled(true);
            }catch(Exception e){
                
            }
        }catch(Exception e){
            i_suma.setBackground(Color.red);
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_i_sumaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField i_data;
    private javax.swing.JComboBox<String> i_kategorija;
    private javax.swing.JTextArea i_komentaras;
    private javax.swing.JTextField i_pavadinimas;
    private javax.swing.JTextField i_suma;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
