/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graf;

import static Lab2.Lab2.toDate;
import ds.FinansuValdymas;
import ds.Kategorija;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author Pacani
 */
public class PajamuIvedimas extends javax.swing.JDialog {
FinansuValdymas a = new FinansuValdymas();
startas pagrSar = new startas();
    /**
     * Creates new form PajamuIvedimas
     */
    public PajamuIvedimas(java.awt.Frame parent, boolean modal, FinansuValdymas a) {
        super(parent, modal);
        this.a = a;
        initComponents();
        ArrayList<Kategorija> kat = a.gautiKategorijuSarasa();
        String[] mas = new String[kat.size()];
        int i=0;
        for(Kategorija k:kat){
            mas[i] = k.getPavadinimas();
            i++;
        }
        p_kategorija.setModel(new javax.swing.DefaultComboBoxModel<>(
                mas
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        p_suma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p_kategorija = new javax.swing.JComboBox<>();
        p_pavadinimas = new javax.swing.JTextField();
        p_data = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        p_komentaras = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pajamu Ivedimas");

        jButton1.setText("Ivesti");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Suma");

        jLabel1.setText("Kategorija:");

        p_suma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                p_sumaKeyReleased(evt);
            }
        });

        jLabel2.setText("Pavadinimas:");

        jLabel3.setText("Data:");

        jLabel4.setText("Komentaras");

        p_kategorija.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        p_kategorija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_kategorijaActionPerformed(evt);
            }
        });

        p_pavadinimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_pavadinimasActionPerformed(evt);
            }
        });

        p_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_dataActionPerformed(evt);
            }
        });
        p_data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                p_dataKeyReleased(evt);
            }
        });

        p_komentaras.setColumns(20);
        p_komentaras.setRows(5);
        jScrollPane1.setViewportView(p_komentaras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(p_kategorija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p_pavadinimas)
                            .addComponent(p_data)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p_suma))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(p_kategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(p_pavadinimas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(p_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(p_suma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String kpav = this.p_kategorija.getSelectedItem().toString();
        String pav = this.p_pavadinimas.getText();
        String data = this.p_data.getText();
        Date dataaa = toDate(data);
        String kom = this.p_komentaras.getText();
        String strSum = this.p_suma.getText();
        double suma = Double.parseDouble(strSum);
        a.pridetiPajama(suma,dataaa,pav,kpav,kom);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void p_kategorijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_kategorijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_kategorijaActionPerformed

    private void p_pavadinimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_pavadinimasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_pavadinimasActionPerformed

    private void p_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_dataActionPerformed

    }//GEN-LAST:event_p_dataActionPerformed

    private void p_dataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_dataKeyReleased
                String datNuo = p_data.getText();
        if(((4 == datNuo.indexOf("-")) && (7 == datNuo.indexOf("-",5)) && datNuo.length()==10) 
                && (datNuo.substring(5, 6).equals("0")||datNuo.substring(5, 6).equals("1")
                &&(datNuo.substring(8, 9).equals("0")||datNuo.substring(8, 9).equals("1")
                ||datNuo.substring(8, 9).equals("2")||datNuo.substring(8, 9).equals("3")))){
            p_data.setBackground(Color.white);
            jButton1.setEnabled(true);

        }else{
            p_data.setBackground(Color.red);
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_p_dataKeyReleased

    private void p_sumaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_sumaKeyReleased
                try{
            Double.parseDouble(p_suma.getText());
            p_suma.setBackground(Color.white);
            try{
            Double.parseDouble(p_suma.getText());
            jButton1.setEnabled(true);
            }catch(Exception e){
                
            }
        }catch(Exception e){
            p_suma.setBackground(Color.red);
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_p_sumaKeyReleased



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField p_data;
    private javax.swing.JComboBox<String> p_kategorija;
    private javax.swing.JTextArea p_komentaras;
    private javax.swing.JTextField p_pavadinimas;
    private javax.swing.JTextField p_suma;
    // End of variables declaration//GEN-END:variables
}
