/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graf;

import ds.FinansuValdymas;
import ds.Kategorija;
import java.util.ArrayList;


public class SalintiKategorija extends javax.swing.JDialog {
FinansuValdymas a = new FinansuValdymas();
    /**
     * Creates new form SalintiKategorija
     */
    public SalintiKategorija(java.awt.Frame parent, boolean modal, FinansuValdymas a) {
        super(parent, modal);
                 this.a = a;
        initComponents();
                ArrayList<Kategorija> kat = a.gautiKategorijuSarasa();
        String[] mas = new String[kat.size()];
        int i=0;
        for(Kategorija k:kat){
            mas[i] = k.getPavadinimas();
            i++;
        }
        sal_kat.setModel(new javax.swing.DefaultComboBoxModel<>(
                mas
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sal_kat = new javax.swing.JComboBox<>();
        salinti_myg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Salinti kategorija");

        jLabel1.setText("Kategorija");

        sal_kat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        salinti_myg.setText("Salinti");
        salinti_myg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salinti_mygActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sal_kat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(salinti_myg)
                        .addGap(0, 75, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sal_kat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(salinti_myg)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salinti_mygActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salinti_mygActionPerformed
        String salKat = this.sal_kat.getSelectedItem().toString();
        a.salintiKategorija(salKat);
        this.dispose();
    }//GEN-LAST:event_salinti_mygActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> sal_kat;
    private javax.swing.JButton salinti_myg;
    // End of variables declaration//GEN-END:variables
}
