/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graf;

import static Lab2.Lab2.toDate;
import ds.FinansuValdymas;
import ds.Islaidos;
import ds.Kategorija;
import ds.PiniguJudejimas;
import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 20173025
 */
public class startas extends javax.swing.JFrame {
    FinansuValdymas afv = new FinansuValdymas();
    KategorijuSarasas katSar = new KategorijuSarasas(afv);
    Date dNuo = null;
    Date dIki = null;
    String tableKategorija;
    String tablePavadinimas;
    String tableTipas;
    String tableData;
    String tableSuma;
    /**
     * Creates new form startas
     */
    public startas() {
        initComponents();
        atnaujintiPagrLentele();
        istrinti_button.setEnabled(false);
        redg_button.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        data_nuo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        data_iki = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filtr_mygt = new javax.swing.JButton();
        redg_button = new javax.swing.JButton();
        istrinti_button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuOpen = new javax.swing.JMenuItem();
        MenuNew = new javax.swing.JMenuItem();
        MenuSave = new javax.swing.JMenuItem();
        MenuQuit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Finansu Valdymo Sistema");

        jLabel1.setText("Data nuo:");

        data_nuo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_nuoActionPerformed(evt);
            }
        });
        data_nuo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                data_nuoKeyReleased(evt);
            }
        });

        jLabel2.setText("Data iki:");

        data_iki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_ikiActionPerformed(evt);
            }
        });
        data_iki.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                data_ikiKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A", "P", "Islaida", "2019-02-03",  new Float(100.5)},
                {"B", "PP", "Pajamos", "2019-03-21",  new Float(200.0)}
            },
            new String [] {
                "Kategorija", "Pavadinimas", "Tipas", "Data", "Suma"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        filtr_mygt.setText("Filtruoti");
        filtr_mygt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtr_mygtActionPerformed(evt);
            }
        });

        redg_button.setText("Redaguoti");
        redg_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redg_buttonActionPerformed(evt);
            }
        });

        istrinti_button.setText("Istrinti");
        istrinti_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                istrinti_buttonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        MenuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        MenuOpen.setText("Atverti finansu faila");
        MenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpenActionPerformed(evt);
            }
        });
        jMenu1.add(MenuOpen);

        MenuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuNew.setText("Pradeti nauja finansu valdyma");
        MenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNewActionPerformed(evt);
            }
        });
        jMenu1.add(MenuNew);

        MenuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        MenuSave.setText("Issaugoti faila");
        MenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSaveActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSave);

        MenuQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        MenuQuit.setText("Baigti darba");
        MenuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuQuitActionPerformed(evt);
            }
        });
        jMenu1.add(MenuQuit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kategorijos");

        jMenuItem5.setText("Kurti nauja kategorija");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem7.setText("Perziureti kategoriju sarasa");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem3.setText("Keisti kategorijos pavadinima");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Salinti kategorija");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Finansai");

        jMenuItem8.setText("Prideti islaidas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Prideti pajamas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Apie");

        jMenuItem2.setText("Apie");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data_nuo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filtr_mygt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(redg_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(istrinti_button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(data_nuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(data_iki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtr_mygt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redg_button)
                    .addComponent(istrinti_button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void rikiuotiData(){
        
    }
    
    public void atnaujintiPagrLentele(){
        ArrayList<Islaidos> isl = afv.gautiIslaiduSarasa();
        ArrayList<PiniguJudejimas> pin = afv.gautiPajamuSarasa();
        Collections.sort(pin);
        Collections.sort(isl);
        String[][] mas = new String[pin.size()+isl.size()][5];
        int i=0;
        for(PiniguJudejimas k:pin){
            if(dIki!=null && dNuo!=null){
            Date thisData = toDate(k.getData());
            if(thisData.before(dNuo)){
                continue;
            }else if(thisData.after(dIki)){
                continue;
            }}
            mas[i][0] = k.getKategorija();
            mas[i][1] = k.getAprasymas();
            mas[i][2] = "Pajamos";
            mas[i][3] = k.getData();
            mas[i][4] = Double.toString(k.getSuma());
            i++;
        }
        for(Islaidos is:isl){
            if(dIki!=null && dNuo!=null){
            Date thisData = toDate(is.getData());
            if(thisData.before(dNuo)){
                continue;
            }else if(thisData.after(dIki)){
                continue;
            }}
            mas[i][0] = is.getIslaidosKategorija();
            mas[i][1] = is.getIslaidosAprasymas();
            mas[i][2] = "Islaidos";
            mas[i][3] = is.getIslaidosData();
            mas[i][4] = Double.toString(is.getIslaiduSuma());
            i++;
        }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                mas,
        new String [] {
                "Kategorija", "Pavadinimas", "Tipas", "Data", "Suma"
            }
        ));
    }
    
    
    private void MenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSaveActionPerformed
         ArrayList<Islaidos> isl = afv.gautiIslaiduSarasa();
                    ArrayList<PiniguJudejimas> pin = afv.gautiPajamuSarasa();
                    ArrayList<Kategorija> kat = afv.gautiKategorijuSarasa();
                    JFileChooser langas = new JFileChooser();
                    int rez = langas.showSaveDialog(null);
        if(rez == JFileChooser.APPROVE_OPTION){
                    File failas2 = langas.getSelectedFile();
                    try {
                        FileWriter faila = new FileWriter(failas2+".afv");
                        for (Kategorija k : kat) {
                            faila.write(k.getPavadinimas() + ";" + k.getAprasymas() + ";"+ "\r\n");
                        }
                        //faila.write("\r\n");
                        for (Islaidos is : isl) {
                            faila.write(is.getIslaiduSuma() + ";" + is.getIslaidosKategorija()
                                    + ";" + is.getIslaidosAprasymas() + ";" + is.getIslaidosKomentaras() + ";"
                                    + is.getIslaidosData() + ";"+ is.getCekioNr() + ";" + "\r\n");
                        }
                        //faila.write("\r\n");
                        for (PiniguJudejimas pj : pin) {
                            faila.write(pj.getSuma() + ";" + pj.getKategorija()
                                    + ";" + pj.getAprasymas() + ";" + pj.getKomentaras() + ";"
                                    + pj.getData() + ";" + "\r\n");
                        }
                        faila.close();
                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Klaida issaugant i faila","Klaida",JOptionPane.ERROR_MESSAGE);
                    }
        }
    }//GEN-LAST:event_MenuSaveActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        KategorijosIvedimas kiv = new KategorijosIvedimas(this, true, afv);
        kiv.setVisible(true);
        katSar.atnaujintiKategorijuLentele();
        katSar.repaint();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void data_nuoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_nuoActionPerformed
        /////////////////
    }//GEN-LAST:event_data_nuoActionPerformed

    private void filtr_mygtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtr_mygtActionPerformed
        String dataN = this.data_nuo.getText();
        String dataI = this.data_iki.getText();
        if(dataN.equals("")){
            dataN = "0000-01-01";
        }if(dataI.equals("")){
            dataI = "9999-12-30";
        }
        
        dNuo = toDate(dataN);
        dIki = toDate(dataI);

        atnaujintiPagrLentele();
    }//GEN-LAST:event_filtr_mygtActionPerformed

    private void MenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpenActionPerformed
    
        JFileChooser langas = new JFileChooser();
        int rez = langas.showOpenDialog(null);
        if(rez == JFileChooser.APPROVE_OPTION){
        File failas1 = langas.getSelectedFile();
        //System.out.println(failas1.getName());
        try {
                        Scanner failas = new Scanner(failas1);
                        while (failas.hasNext()) {
                            String eilute = failas.nextLine();
                            String[] dalys = eilute.split(";");
                            if (dalys.length == 2) {
                                String pavad = dalys[0];
                                String apras = dalys[1];
                                afv.pridetiKategorija(pavad, apras);
                            }
                            String[] dalys1 = eilute.split(";");
                            if (dalys1.length == 6) {
                                double sum = Double.parseDouble(dalys1[0]);
                                String katt = dalys1[1];
                                String apr = dalys1[2];
                                String kome = dalys1[3];
                                Date date1 = toDate(dalys1[4]);
                                String cekionr = dalys1[5];
                                afv.pridetiIslaida(sum, date1, apr, katt, kome, cekionr);
                            }
                            String[] dalys2 = eilute.split(";");
                            if (dalys2.length == 5) {
                                double sum = Double.parseDouble(dalys2[0]);
                                String katp = dalys2[1];
                                String apr = dalys2[2];
                                String kome = dalys2[3];
                                Date date1 = toDate(dalys2[4]);
                                afv.pridetiPajama(sum, date1, apr, katp, kome);
                            }
                        }
                        failas.close();
                    }catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Klaida nuskaitant faila","Klaida",JOptionPane.ERROR_MESSAGE);
                    }
    }
        katSar.atnaujintiKategorijuLentele();
        atnaujintiPagrLentele();
    }//GEN-LAST:event_MenuOpenActionPerformed

    private void MenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNewActionPerformed
        FinansuValdymas afv = new FinansuValdymas();
        atnaujintiPagrLentele();
    }//GEN-LAST:event_MenuNewActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        katSar.atnaujintiKategorijuLentele();
        katSar.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void MenuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuQuitActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        IslaiduIvedimas isv = new IslaiduIvedimas(this, true, afv);
        isv.setVisible(true);
        atnaujintiPagrLentele();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        PajamuIvedimas piv = new PajamuIvedimas(this, true, afv);
        piv.setVisible(true);
        atnaujintiPagrLentele();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Apie ap = new Apie(this,true);
        ap.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    RedaguotiKategorija rkat = new RedaguotiKategorija(this, true, afv);
    rkat.setVisible(true);
    katSar.atnaujintiKategorijuLentele();
    katSar.repaint();
    atnaujintiPagrLentele();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void data_nuoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_data_nuoKeyReleased
        String datNuo = data_nuo.getText();
        if((((4 == datNuo.indexOf("-")) && (7 == datNuo.indexOf("-",5)) && datNuo.length()==10) 
                && (datNuo.substring(5, 6).equals("0")||datNuo.substring(5, 6).equals("1")
                &&(datNuo.substring(8, 9).equals("0")||datNuo.substring(8, 9).equals("1")
                ||datNuo.substring(8, 9).equals("2")||datNuo.substring(8, 9).equals("3"))))||datNuo.equals("")){
            data_nuo.setBackground(Color.white);
            filtr_mygt.setEnabled(true);

        }else{
            data_nuo.setBackground(Color.red);
            filtr_mygt.setEnabled(false);
        }
    }//GEN-LAST:event_data_nuoKeyReleased

    private void data_ikiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_data_ikiKeyReleased
         String datNuo = data_iki.getText();
        if((((4 == datNuo.indexOf("-")) && (7 == datNuo.indexOf("-",5)) && datNuo.length()==10) 
                && (datNuo.substring(5, 6).equals("0")||datNuo.substring(5, 6).equals("1")
                &&(datNuo.substring(8, 9).equals("0")||datNuo.substring(8, 9).equals("1")
                ||datNuo.substring(8, 9).equals("2")||datNuo.substring(8, 9).equals("3"))))||datNuo.equals("")){
            data_iki.setBackground(Color.white);
            filtr_mygt.setEnabled(true);

        }else{
            data_iki.setBackground(Color.red);
            filtr_mygt.setEnabled(false);
        }
    }//GEN-LAST:event_data_ikiKeyReleased

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       SalintiKategorija sKat = new SalintiKategorija(this, true, afv);
    sKat.setVisible(true);
    katSar.atnaujintiKategorijuLentele();
    katSar.repaint();
    atnaujintiPagrLentele();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void istrinti_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_istrinti_buttonActionPerformed
        double suma = Double.parseDouble(tableSuma);
        Date data = toDate(tableData);
        if(tableTipas.equals("Pajamos")){
            afv.salintiPajama(suma , data, tablePavadinimas, tableKategorija);
        }else{
            afv.salintiIslaida(suma , data, tablePavadinimas, tableKategorija);
        }
        atnaujintiPagrLentele();
        istrinti_button.setEnabled(false);
        redg_button.setEnabled(false);
    }//GEN-LAST:event_istrinti_buttonActionPerformed

    private void redg_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redg_buttonActionPerformed
    Redaguoti redg = new Redaguoti(this,true,afv,tableKategorija,tablePavadinimas,tableTipas
            ,tableData,tableSuma);
    redg.setVisible(true);
    atnaujintiPagrLentele();
    redg_button.setEnabled(false);
    istrinti_button.setEnabled(false);
    }//GEN-LAST:event_redg_buttonActionPerformed

    private void data_ikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_ikiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_ikiActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     istrinti_button.setEnabled(true);
     redg_button.setEnabled(true);
        try{
     DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
     int selectedRowIndex = jTable1.getSelectedRow();
     tableKategorija = model.getValueAt(selectedRowIndex, 0).toString();
     tablePavadinimas = model.getValueAt(selectedRowIndex, 1).toString();
     tableTipas = model.getValueAt(selectedRowIndex, 2).toString();
     tableData = model.getValueAt(selectedRowIndex, 3).toString();
     tableSuma = model.getValueAt(selectedRowIndex, 4).toString();
     }catch(Exception ex){
         istrinti_button.setEnabled(false);
         redg_button.setEnabled(false);
     }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuNew;
    private javax.swing.JMenuItem MenuOpen;
    private javax.swing.JMenuItem MenuQuit;
    private javax.swing.JMenuItem MenuSave;
    private javax.swing.JTextField data_iki;
    private javax.swing.JTextField data_nuo;
    private javax.swing.JButton filtr_mygt;
    private javax.swing.JButton istrinti_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton redg_button;
    // End of variables declaration//GEN-END:variables
}
